name: Build & Deploy Airways

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-deploy:
    name: Build and Deploy Airways
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17



      - name: Build the application
        run: |
          mvn compile
          mvn -B package --file pom.xml
